version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network
    restart: always

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_data:
